import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav";
import Footer from "@/components/footer";
import { Inter, Lora, Alegreya, Lato, Montserrat } from 'next/font/google';

export const lora = Lora({ subsets: ["latin"], variable: "--font-lora" });
export const lato = Lato({ weight: ["100", "300", "400", "700", "900"], subsets: ["latin"], variable: "--font-lato" });
export const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-montserrat" });
export const inter = Inter({ subsets: ['latin'], variable: '--font-sans'});
export const alegreya = Alegreya({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-alegreya' });
export const geistSans = localFont({ src: "./fonts/GeistVF.woff", variable: "--font-geist-sans", weight: "100 900", });
export const geistMono = localFont({ src: "./fonts/GeistMonoVF.woff", variable: "--font-geist-mono", weight: "100 900",});

export const metadata = {
  title: "CarePath",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${lora.variable} ${lato.variable} ${montserrat.variable} font-sans`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
